name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: 'true'

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install library dependencies
      run: pio lib -g install 1
    - name: Run PlatformIO
      working-directory: ./Mini-SSS3-Firmware
      run: pio run -e teensy40
    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-hex-file
        path: ./Mini-SSS3-Firmware/.pio/build/teensy40/firmware.hex


